### ISSUE TITLE
Switching to the rightmost pane with keyboard shortcuts does not animate.

### ISSUE THREAD

**Issue by taylorhadden** [deathau/sliding-panes-obsidian#17]
This is a pretty minor issue, but a little jarring.

In this recording, I first select the panes with the mouse, which works as expected. Then I go back to the left and switch between the panes with the keyboard shortcut.

![Screen Recording 2020-11-05 at 12 52 01 PM](https://user-images.githubusercontent.com/15878743/98278835-26530680-1f67-11eb-95fe-454e2412d536.gif)

**Comment by deathau** [comment]
I think I can replicate, and it's a bit weirder than that. If I have a bunch of edit mode panes open, then use the keyboard shortcut to cycle between them, it's like only every second one animates (at least on my machine). I'm guessing there's something internal (possibly in CodeMirror) that is somehow doing the scroll (non-animated) for me.

I'll investigate further.

**Comment by deathau** [comment]
Yeah, doing some investigative logging and there is definitely something weird going on. 

I got to the point where I'm overwriting the `workspace.setActiveLeaf` function to insert some logs and see what's going on, but it's leaving me with more questions than answers. I'm testing as above by opening a bunch of panes then using the keyboard shortcut for switch to right pane multiple times.

Every time I switch panes, it seems that `setActiveLeaf` is called twice. Every second switch though, something changes between the first and second `setActiveLeaf` call, and the `rootSplit.containerEl.scrollLeft` has shifted by itself before I've gotten a chance to calculate where it _should_ scroll to. And because that scroll has happened without my code, I can't do anything about making that scroll smooth.

I think I'll need to ping Licat for some help on what might be happening internally and if there's a way around it.

**Comment by deathau** [comment]
Okay, I worked out something... It's not every _second_ pane, it's every transition to a pane which is less than 45(ish) pixels from the right edge. I have a somewhat hacky workaround that takes that magic 45 pixels into consideration by scrolling 45 pixels "too far".

**Comment by deathau** [comment]
So, thanks to Licat, I found the _true_ cause of this issue was actually electron auto-focusing on the active cursor in the editor. Which, luckily for us is in a completely invisible text box that I can shift around with CSS and no one will notice.

So I've done some trickery to make the invisible text box of the previous and next panes "in view" so that the cursor won't be jumping off screen and everything animates nicely.

If you switch too quickly (for example there's a future shortcut to jump to the first or last panes — or you just press the hotkey too quickly) it could still jump without the animation. But this works in most cases for now.l
