### ISSUE TITLE
Leaf Auto Width opens new file "offscreen"

### ISSUE THREAD

**Issue by greenmanspirit** [deathau/sliding-panes-obsidian#32]
I am noticing that with auto width on, when I open a new file, the spine is off the screen. The gif below shows what happens.

![andy-mode-auto-width-bug](https://user-images.githubusercontent.com/31684/100145642-9d910180-2e66-11eb-8191-9f7d1207704d.gif)

**Comment by deathau** [comment]
It looks like this was caused by a typo in my code, actually.
From the next release it should open that spine in view, and the scroll bar should be correct. It still won't scroll to the newly opened pane automatically, because Obsidian doesn't activate that new pane in this scenario. But it least it won't be off-screen 😄
